# Algorithm Validation
*Author: Yasel Garces (88yasel@gmail.com)*
## Introduction
Rotavirus genome replication and assembly take place in cytoplasmic electron dense inclusions termed viroplasms (VPs). Previous conventional optical microscopy studies observing the intracellular distribution of rotavirus proteins and their organization in VPs have lacked
molecular-scale spatial resolution, due to inherent spatial resolution constraints. In our paper ''Nanoscale organization of rotavirus replication machineries'' [eLife, please include link] we employed super-resolution microscopy to reveal the nanometric-scale organization of VPs formed
during rotavirus infection, and quantitatively describe the structural organization of seven viral proteins within and around the VPs. For this, we developed a segmentation algorithm based on a least squares approach, which we called ''Viroplasm Direct Least Squares Fitting Circumference'' (VP-DLSFC) (see ''Segmentation Algorithm'' in Appendix 1 in [INCLUDE LINK TO PAPER]), to measure the spatial distribution of the components within individual VPs by adjusting concentric circumferences. This method is automatic, deterministic, easy to implement, and has a linear computational complexity. 

The performance of VP-DLSFC was tested on approximately 40,000 ''ground truth'' (GT) synthetic images, showing a high robustness to noise and partial occlusion scenarios. Additionally, we compared our method with two other alternative methods, ''Algebraic Least Square Fitting Circle'' (ALSFC) and Geometric Least Square Fitting Circle'' (GLSFC) ([Gander et al., 1994](https://link.springer.com/article/10.1007/BF01934268)), and our approach displayed an improved performance (see [LINK TO PAPER]).

## Validation Details
For the validation, we simulated the spatial distribution of viral elements as circum-
ferences, for which we know their parametric form (''ground truth'' dataset) (Appendix 1
Figure 2A in [CITE PAPER HERE). The use of ''ground truth'' allows us to quantify the error in the adjustment of the algorithms DLSFC, ALSFC and GLSFC at different noise levels (Appendix 1 Figure 2B in [CITE PAPER HERE)) and partial occlusion conditions (Appendix 1 Figure 2C in [CITE PAPER HERE)). We generated over 40 000 images (size $512\times 512$ pixels) taking into account different levels of additive white Gaussian noise (AWGN) in order to consider auto-fluorescence and the error in the localization of the fluorophores by the algorithm 3B-ODE (see Appendix 1 Section 1), and partial occlusion angles. Several radii and position of the synthetic viroplasms were generated randomly through a uniform distribution function.

Interested in more details? Please see this paper here [LINK TO PAPER].

## Files in this Directory
This directory is composed by 7 files, these are:

1. **Run_Algorithm_Validation.m**: Matlab script. Allow the simulation of the images with different occlusion angles and noise levels and make the comparison between the VP-DLSFC, ALSFC and GLSFC algorithms.
2. **draw ellipse.m**: Matlab script. This function generates the points of an ellipse using the parametric representation and polar coordinates system of this primitive (see [here](https://en.wikipedia.org/wiki/Ellipse#Polar_forms) for details).
3. **fitcircle.m**: This is a third part function obtained from [File Exchange MathWorks](https://www.mathworks.com/matlabcentral/fileexchange/15060-fitcircle-m) that compute the algorithms ALSFC and GLSFC. ''This implementation copyright Richard Brown, 2007, but is freely available to copy, use, or modify as long as this line is maintained''. 
4. **fit_circumference_LSFC.m**: Matlab script. This function adjusts a circumference to a set of points in R^2 through the algorithm VP-DLSFC (see [LINK TO PAPER] for details).
5. **circle_std.m**: Matlab script. It computes the mean and the standard deviation of the distance of a set of points to a circumference.
6. **Statistical_Analysis.R**: R script. It performs the statistical analysis of the data generated by the simulation described above.
7. **SimulationResult.csv**: This file contains all the results of the simulations.

All the results obtained in this section are reproducible through these codes, and even when a new validation set of image is generated, you are going to obtain very similar results than those presented here (this is because the validation use a high number of images for the same experimental conditions, so we obtain a high convergence in the final results).