#' Analysis of the validation data generated by the simulation.
#' @param Simulation.csv: It is only necessary to have in 
#' the directory this files with the results of the ssimulation.
#' @return BoxplotError.pdf: Boxplot of the error generated by algorithm 
#' and occlussion angle.
#' @return PlotErrorAlgorithm.pdf: Line plot with the error by algorithm 
#' and occlussion angle.
#' @return PlotErrorDLSFC.pdf: Error of the algorithm DLSFC.
#' @return PlotErrorDLSFC_ALSFC.pdf: Error of the algorithms DLSFC and ALSFC.
#' @return Binomila test results for all the algorithms and partial occlussion angles.
#' @author Yasel Garces (88yasel@gmail.com)
#' @note For details consult the paper: Nanoscale organization of rotavirus replication machineries, eLife.

# Load libraries
library(ggplot2)
library(cowplot)
library(dplyr)
library(scales)
library(RColorBrewer)
# Set cowplot theme
theme_set(theme_cowplot())
#----------------------------------------------------------------------------------------
# Load work directory
setwd('/home/yasel/Dropbox/Paper Viroplasmas/Programs/AlgorithmValidation')
# Load data
validation<-read.csv(file = 'SimulationResult.csv')
# Transform variables
validation$ID<-as.factor(validation$ID)
validation$Angle<-as.factor(validation$Angle)
validation$Angle <- factor(validation$Angle, levels = levels(validation$Angle)[c(4,3,2,1)],
                           labels = c(expression(0),expression(frac(pi,2)),
                                      expression(pi),expression(frac(3*pi,2))))
validation$Algorithm <- factor(validation$Algorithm, levels = levels(validation$Algorithm)[c(3,2,1)])

# Considerer the mean by each hour
resume <- summarise(group_by(validation,ID,Algorithm,Angle),
                    MeanDistance=mean(DistanceMean),StdDistance=mean(DistanceStd),
                    MeanError=mean(Error),StdError=sd(Error))
#Create a custom color scale
myColors <- c("red","blue","green")
names(myColors) <- levels(validation$Algorithm)
colScale <- scale_colour_manual(name = "Algorithm",values = myColors)
#----------------------------------------------------------------------------------------
# FIGURES
# Boxplot of the error generated by algorithm and occlussion angle. 
pdf("BoxplotError.pdf",width=5,height=5)
ggplot(data = validation,aes(x=Algorithm,y = Error,fill=Algorithm))+geom_boxplot(notch = TRUE)+
  theme(legend.position = "",axis.text.x = element_text(angle = 45, hjust = 1))+
  ylab(expression(paste("Error"," ","(",mu,m,")")))+
  facet_grid(.~ Angle,labeller = label_parsed)+geom_hline(yintercept = 0.1732,color="black")+
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)))+
  geom_rect(data = subset(validation, Angle == "frac(3 * pi, 2)"),xmin = -Inf,xmax = Inf,
            ymin = -Inf,ymax = Inf,fill="blue",alpha = 0.002)+colScale+
  scale_fill_manual(values=c("red","blue","green"))
dev.off()
#----------------------------------------------------------------------------------------
# Line plot with the error by algorithm and occlussion angle.
pdf("PlotErrorAlgorithm.pdf",width=5,height=5)
ggplot(data = resume,aes(x=MeanDistance,y = MeanError,group=Algorithm,color=Algorithm))+geom_line()+
  theme(legend.position = "bottom")+ylab(expression(paste("Mean Error"," ","(",mu,m,")")))+
  facet_grid(Angle~.,labeller = label_parsed)+scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                                                            labels = trans_format("log10", math_format(10^.x)))+
  scale_x_continuous(breaks = round(seq(min(resume$MeanDistance), max(resume$MeanDistance), length.out = 7),1),
                     name = expression(paste("Mean Points Distance"," ","(",mu,m,")")),
                     sec.axis = sec_axis(~ . * 1, 
                                         breaks = round(seq(min(resume$MeanDistance), 
                                                            max(resume$MeanDistance), length.out = 7),1), 
                                         labels = round(seq(min(resume$StdDistance), 
                                                            max(resume$StdDistance), length.out = 7),1),
                                         name = "Standard Deviation"))+
  colScale
dev.off()
#----------------------------------------------------------------------------------------
# Subset data (only GLSFC)
test<-subset(resume,subset = Algorithm==c("DLSFC"))
# Error of the algorithm DLSFC.
pdf("PlotErrorDLSFC.pdf",width=5,height=5)
ggplot(data = test,aes(x=MeanDistance,y = MeanError,color=Algorithm))+geom_line()+
  theme(legend.position = "none")+ylab(expression(paste("Mean Error"," ","(",mu,m,")")))+
  facet_grid(Angle~.,labeller = label_parsed)+ geom_ribbon(aes(ymax = MeanError + StdError, 
                                                               ymin= MeanError - StdError,
                                                               fill = Algorithm),linetype="blank",alpha=0.3)+
  scale_x_continuous(breaks = round(seq(min(resume$MeanDistance), max(resume$MeanDistance), length.out = 7),1),
                     name = expression(paste("Mean Points Distance"," ","(",mu,m,")")),
                     sec.axis = sec_axis(~ . * 1, 
                                         breaks = round(seq(min(resume$MeanDistance), 
                                                            max(resume$MeanDistance), length.out = 7),1), 
                                         labels = round(seq(min(resume$StdDistance), 
                                                            max(resume$StdDistance), length.out = 7),1),
                                         name = "Standard Deviation"))+colScale+
  scale_fill_manual(values=c("blue"))+geom_hline(yintercept = 0.1732)
dev.off()
#----------------------------------------------------------------------------------------
# Include only the algorithms VP-DLSFC and ALSFC
test<-filter(resume,Algorithm!=c("GLSFC"))
# Error of the algorithms DLSFC and ALSFC.
pdf("PlotErrorDLSFC_ALSFC.pdf",width=5,height=5)
ggplot(data = test,aes(x=MeanDistance,y = MeanError,color=Algorithm))+geom_line()+
  theme(legend.position = "none",axis.text.x = element_text(angle = 90, hjust = 1))+
  ylab(expression(paste("Mean Error"," ","(",mu,m,")")))+
  facet_grid(Angle~Algorithm,labeller = label_parsed)+ geom_ribbon(aes(ymax = MeanError + StdError, 
                                                                       ymin= MeanError - StdError,
                                                                       fill = Algorithm),linetype="blank",
                                                                   alpha=0.2)+
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)))+
  scale_x_continuous(breaks = round(seq(min(resume$MeanDistance), max(resume$MeanDistance), length.out = 7),1),
                     name = expression(paste("Mean Points Distance"," ","(",mu,m,")")),
                     sec.axis = sec_axis(~ . * 1, 
                                         breaks = round(seq(min(resume$MeanDistance), 
                                                            max(resume$MeanDistance), length.out = 7),1), 
                                         labels = round(seq(min(resume$StdDistance), 
                                                            max(resume$StdDistance), length.out = 7),1),
                                         name = "Standard Deviation"))+colScale+
  scale_fill_manual(values=c("blue","green"))+geom_hline(yintercept = 0.1732)

dev.off()
# ---------------------------------------------------
# Binomila test for all the algorithms and partial occlussion angles.
library(plyr)
# Successful number of fit in Radius
adjust<-ddply(validation, c("Algorithm","Angle"), function(x) sum(abs(x$Error)<0.1732))
total<-ddply(validation, c("Algorithm","Angle"), function(x) length(x$Error))
# Hypothesis test (Test of Equal or Given Proportions)
by(adjust,
   adjust[,c("Algorithm","Angle")],
   function(x) binom.test(x$V1,10000,p =0.7,alternative = "greater"))
#----------------------------------------------------------